#!/usr/bin/env bash
## To enable this check, copy this file into your .git/hooks/ directory.
## Or symlink using `ln -s pre-commit .git/hooks/pre-commit`

if ! grep -iq "ENC#~" .env; then
echo " Not encrypted: .env"; exit 1; fi

## Add more files if necessary.
